### ISSUE TITLE
upath breaks my Object.prototype inheritance

### ISSUE THREAD

**Issue by alejo-jm** [anodynos/upath#22]
for example if create some Object.prototype like this:
```
Object.prototype.myCustomFun  = () => {
}
```
this will break my node.js app with the message:
```
./node_modules/upath/build/code/upath.js:163
    throw new Error("path." + name + " already exists.");
    ^
Error: path.myCustomFun already exists.
    at Object.<anonymous> (./node_modules/upath/build/code/upath.js:163:11)

```
Why we need to check upath[name] !== void 0:

```
for (name in extraFunctions) {
  extraFn = extraFunctions[name];
  if (upath[name] !== void 0) {
    throw new Error("path." + name + " already exists.");
  } else {
    upath[name] = extraFn;
  }
}
```

**Comment by anodynos** [comment]
Good catch! I'll fix it with 3 letters in coffeescript :-)

On the other hand, keep in mind it's not wise at all to augment **existing prototypes**, especially `Object`! Just because you can, doesn't mean you should!

This property `myCustomFun` will creep up in every object that you have in hand (as it happened here), in enumerations (which you can hide with `Object.defineProperty` and set it to non-enumerable), but also it will appear in EVERY object, when you access it or check if it exists as in `mySomeOtherObject.myCustomFun !== undefined`.

**Comment by alejo-jm** [comment]
Excellent !!!!!
