### ISSUE TITLE
Node v10.x Incompatibility

### ISSUE THREAD

**Issue by kaufmann42** [anodynos/upath#23]
Error Message:
`upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9"`

when upgrading to node 10.x, any problem with upgrading node for this module?

**Comment by davityavryan** [comment]
Seems like they already have a support for 10.x see [commit](https://github.com/anodynos/upath/commit/cee9c254665e34b6cf606c8278f7678f549a7234).

If you encountered this issue because of Webpack, just check your lock files. In my case I just did `yarn remove webpack` and `yarn add webpack` which updated the whole chain and installed upath@1.1.0 as of it is hoisted from "webpack#watchpack#chokidar#upath".

**Comment by kedoska** [comment]
I removed `yarn.lock`, after that everything worked fine.
