### ISSUE TITLE
upath.join goes above C:\

### ISSUE THREAD

**Issue by aicioara** [anodynos/upath#31]
**Expected:**

```js
> upath.join('C:/', '..')
'C:/'
```

**Actual**

```js
> upath.join('C:\\', '..')
'.'
```

**Comment by anodynos** [comment]
You have a good point here, but I'm not sure which is best in order to have consistency with `path`: 
``
console.log(upath.join('C:\\', '..')) // '.'
console.log(path.join('C:\\', '..'))  // '.'

console.log(upath.join('C:/', '..')) // '.'
console.log(path.join('C:/', '..'))  // '.'

console.log(upath.join('/', '..'))  // '/'
console.log(path.join('/', '..'))   // '/'

console.log(upath.join('/', '../..'))  // '/'
console.log(path.join('/', '../..'))  //  '/'
```

**Comment by aicioara** [comment]
Would adding it behind a trigger be a sensible choice?

**Comment by anodynos** [comment]
What do you mean by `trigger`? An option?
If so, I don't think we should change the behaviour to the vanilla `path` module, only add new ones :-)

**Comment by anodynos** [comment]
But I can see the confusion. 
I think it would be better if we have consistency between systems, which ofcourse would be a breaking change. 

Now I am thinking that the best result would simply be `null`, which would mean *over the edge*. And since we're having breaking changes, why not go with what's actually the better choice?

**Comment by aicioara** [comment]
You are correct. I meant an option. I am not sure if a breaking change is the way to go though.

If anything, having `null` mean _over the edge_ could potentially be a bad choice, in my opinion. The idea scenario is where we can make the edge "sticky", so we never go past it. Returning `null` is particularly problematic in the following cases

```js
console.log(upath.join('C:/', '..')) // null - how do we recover C:/ ?
console.log(upath.join('D:/', '..')) // null - how do we recover D:/ ?
```

**Comment by anodynos** [comment]
Yeah, I see those points also. 
I think it should just be a couple of helper methods: 
 - `joinSafe()` => returning always the right root (`/` or `c:\`) 
 - `joinNull()` => returning null if falling off the cliff! I'm open to names :-)

**Comment by aicioara** [comment]
+1 for `joinSafe()`.

**Comment by anodynos** [comment]
Yes, I'd love a PR @aicioara :-)

**Comment by anodynos** [comment]
Closing cause it's stale
